### ISSUE TITLE
Issue Found

### ISSUE THREAD

**Issue by mclark41** [marcodrubens/VERSO-UVM-CS-2300-Back-Left#11]
https://github.com/marcodrubens/VERSO-UVM-CS-2300-Back-Left/blob/b3628a4ec8b3cef8eb7773593bafb0d1a23a0d45/programming%20files/remove_duplicates.py#L15
Instead of discarding duplicates into the discarded array it is put into unique array. To solve this issue you can change the array to removed_elements instead of unique_arr. This issue occurs in line 15

**Comment by heidelbergah** [comment]
Line 15 updated. Additional spelling errors have been fixed in addition.
