### ISSUE TITLE
rgb_to_hex.py Issue

### ISSUE THREAD

**Issue by Matt-Swaim** [marcodrubens/VERSO-UVM-CS-2300-Back-Left#12]
Description: There are semicolons at the end of the line when there should not be

Steps to Reproduce: The bug does not require reproduction, it is an inherent issue and so it will affect the program when it is run

Expected Behavior: The program is expected to change an RGB value to a hex value.

Actual Behavior: The program does not work because of the semi colons

Additional Information

Operating System: Windows
Browser: Chrome
Possible Solution: Remove semi colons from lines

Related Issues Are there any related issues? If so, please link to them here.

Priority: This is high priority- the program will not function without it

Reproducibility: Will always be reproduced as long as there are semicolons at the end of the lines

Impact: High- the program will not function without it

**Comment by owenmilke** [comment]
Removed unnecessary semicolons.
